version: '3'

services:
    db:
        container_name: boxing-db
        build:  
            context: ./database
        ports:
            - "8001:3306"
        volumes:
            - mydb:/var/lib/mysql
            - ./database/db_upgrades:/var/db_upgrades
    
    web:
        container_name: boxing-web
        build:
            context: ./webapp
        ports:
            - "8000:80"
        depends_on: 
            - db
        links:
            - "db:mysql"
        volumes:
            - ./webapp/html:/usr/lib/html
            - ./webapp/cgi-bin:/usr/lib/cgi-bin

volumes:
    mydb: